services:
    web:
        build: ./backend
        # command: python manage.py runserver 0.0.0.0:8000
        command: gunicorn src.wsgi:application --bind 0.0.0.0:8000
        
        volumes:
            - ./backend/src:/src

        ports:
            - 8000:8000

        env_file:
        #    - ./backend/src/.env
            - ./.env

    nginx:
        build: ./frontend

        ports:
            - 80:80
        
        volumes:
            - /var/www/html:/home/nginxuser/images  
        
        depends_on:
            - web
