services:
  web:
    build:
      context: ./backend/src

    command: gunicorn src.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - ./backend/src/:/src
      - static_files:/src/staticfiles

    expose:
      - 8000

    ports:
      - 8000:8000
    
    env_file:
      - ./backend/.env