services:
  web:
    build:
      context: ./src
    # command: python manage.py runserver 0.0.0.0:8000
    command: gunicorn src.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - ./src/:/src
    ports:
      - 8000:8000
    
    env_file:
      - ./.env