# Generated by Django 4.2.7 on 2024-11-18 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('deposit_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('deposit_excel', models.FileField(blank=True, null=True, upload_to='')),
                ('deposit_state', models.CharField(max_length=16)),
                ('deposit_creation_date', models.DateTimeField()),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('affiliation', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'deposits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('request_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('request_state', models.CharField(max_length=16)),
                ('request_creation_date', models.DateTimeField()),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('affiliation', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('strains_requested', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Strains',
            fields=[
                ('strain_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('ccasm_id', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='CCASM ID must be in the format CCASM-xxxxxx, where x is a digit.', regex='^CCASM-\\d{6}$')])),
                ('strain_name', models.CharField(blank=True, max_length=128, null=True)),
                ('binomial_classification', models.CharField(blank=True, max_length=128, null=True)),
                ('taxonomic_lineage', models.TextField(blank=True, null=True)),
                ('risk_group', models.IntegerField(blank=True, null=True)),
                ('is_plant_pathogen', models.BooleanField(blank=True, null=True)),
                ('colony_morphology', models.CharField(blank=True, max_length=128, null=True)),
                ('host_plant_species', models.CharField(blank=True, max_length=128, null=True)),
                ('isolation_source', models.CharField(blank=True, max_length=64, null=True)),
                ('isolation_year', models.IntegerField(blank=True, null=True)),
                ('isolation_protocol', models.CharField(blank=True, max_length=25, null=True)),
                ('isolation_growth_medium', models.CharField(blank=True, max_length=128, null=True)),
                ('isolation_growth_temperature', models.IntegerField(blank=True, null=True)),
                ('isolation_growth_medium_composition', models.CharField(blank=True, max_length=128, null=True)),
                ('isolation_soil_ph', models.FloatField(blank=True, null=True)),
                ('isolation_soil_organic_matter', models.CharField(blank=True, max_length=128, null=True)),
                ('isolation_soil_texture', models.CharField(blank=True, max_length=128, null=True)),
                ('isolation_soil_province', models.CharField(blank=True, max_length=2, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('genome_ncbi_association', models.CharField(blank=True, max_length=128, null=True)),
                ('genome_size', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('citation', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=1024, null=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'strains',
                'managed': True,
            },
        ),
    ]
