# Generated by Django 4.2.7 on 2024-11-23 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposits',
            name='deposit_excel',
        ),
        migrations.AlterField(
            model_name='strains',
            name='ccasm_id',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='CCASM ID must be in the format CCASM-xxxxxx, where x is a digit.', regex='^CCASM_\\d{6}$')]),
        ),
    ]
